use serde::{Serialize, de::DeserializeOwned};
use std::fs;
use std::path::PathBuf;
use std::sync::{Arc, OnceLock};

// ═══════════════════════════════════════════════════════════════════
//  StorageBackend trait
// ═══════════════════════════════════════════════════════════════════

/// Abstract storage backend for i-rs CLI tool data persistence.
///
/// ## Purpose
///
/// All 70 `i-rs-{name}` tools use `load_store()` / `save_store()` generated by
/// the `create_store!` macro.  Those functions internally create a `Storage<T>`
/// which delegates I/O to the globally-registered `StorageBackend`.
///
/// **Default**: `FileBackend` → `~/.i-rs/data/{name}.json`.  Zero config.
///
/// **Override**: call `set_backend()` early (before any store operation) to
/// redirect all tool I/O — e.g., to a remote API.
///
/// ```ignore
/// // Third-party tool using a custom API backend
/// i_rs_core::storage::set_backend(Arc::new(MyApiBackend::new("https://...")));
/// // From here on, all load_store() / save_store() calls go through MyApiBackend
/// ```
pub trait StorageBackend: Send + Sync + 'static {
    /// Read raw JSON content for a tool.  `None` = no data yet (triggers default init).
    fn read(&self, filename: &str) -> anyhow::Result<Option<String>>;
    /// Write raw JSON content for a tool.
    fn write(&self, filename: &str, content: &str) -> anyhow::Result<()>;
}

// ═══════════════════════════════════════════════════════════════════
//  FileBackend (default)
// ═══════════════════════════════════════════════════════════════════

/// Default storage backend: JSON files under `~/.i-rs/data/`.
pub struct FileBackend {
    data_dir: PathBuf,
}

impl FileBackend {
    pub fn new(data_dir: PathBuf) -> Self {
        Self { data_dir }
    }

    fn file_path(&self, filename: &str) -> PathBuf {
        self.data_dir.join(format!("{}.json", filename))
    }
}

impl StorageBackend for FileBackend {
    fn read(&self, filename: &str) -> anyhow::Result<Option<String>> {
        let path = self.file_path(filename);
        if !path.exists() {
            return Ok(None);
        }
        let file = fs::File::open(&path)?;
        fs2::FileExt::lock_shared(&file)?;
        let content = fs::read_to_string(&path)?;
        drop(file);
        Ok(Some(content))
    }

    fn write(&self, filename: &str, content: &str) -> anyhow::Result<()> {
        let path = self.file_path(filename);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let file = fs::File::create(&path)?;
        fs2::FileExt::lock_exclusive(&file)?;
        fs::write(&path, content)?;
        drop(file);
        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Global backend registry
// ═══════════════════════════════════════════════════════════════════

static GLOBAL_BACKEND: OnceLock<Arc<dyn StorageBackend>> = OnceLock::new();

fn default_data_dir() -> PathBuf {
    if let Ok(env_dir) = std::env::var("CONFIG_DIR") {
        return PathBuf::from(env_dir);
    }
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".i-rs")
        .join("data")
}

fn get_backend() -> Arc<dyn StorageBackend> {
    GLOBAL_BACKEND
        .get()
        .cloned()
        .unwrap_or_else(|| Arc::new(FileBackend::new(default_data_dir())))
}

/// Override the global storage backend. Call once at startup, before any
/// `load_store()` / `save_store()` invocation.
///
/// ```ignore
/// i_rs_core::storage::set_backend(Arc::new(MyApiBackend::new("https://api.example.com")));
/// ```
pub fn set_backend(backend: Arc<dyn StorageBackend>) {
    let _ = GLOBAL_BACKEND.set(backend);
}

// ═══════════════════════════════════════════════════════════════════
//  Storage<T> — the type used by create_store! macro
// ═══════════════════════════════════════════════════════════════════

pub struct Storage<T> {
    pub data: T,
    filename: String,
}

impl<T: Default> Default for Storage<T> {
    fn default() -> Self {
        Self {
            data: T::default(),
            filename: String::new(),
        }
    }
}

impl<T: Serialize + DeserializeOwned + Default> Storage<T> {
    #[must_use]
    pub fn new(filename: &str) -> Self {
        Self {
            data: T::default(),
            filename: filename.to_string(),
        }
    }

    /// Load data from the backend.  Returns default if no data exists yet.
    pub fn load(&mut self) -> anyhow::Result<&mut T> {
        let backend = get_backend();
        match backend.read(&self.filename)? {
            Some(content) => {
                self.data = serde_json::from_str(&content)
                    .map_err(|e| anyhow::anyhow!("Failed to parse {}: {}", self.filename, e))?;
            }
            None => {
                // No file yet — keep default and create directory for file backend
                let data_dir = default_data_dir();
                let _ = fs::create_dir_all(&data_dir);
            }
        }
        Ok(&mut self.data)
    }

    /// Save data to the backend.
    pub fn save(&self) -> anyhow::Result<()> {
        self.save_data(&self.data)
    }

    /// Save arbitrary data without modifying `self.data`.
    pub fn save_data(&self, data: &T) -> anyhow::Result<()> {
        let content = serde_json::to_string_pretty(data)
            .map_err(|e| anyhow::anyhow!("Failed to serialize: {}", e))?;
        get_backend().write(&self.filename, &content)
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Utilities
// ═══════════════════════════════════════════════════════════════════

pub trait HasTags {
    fn tags(&self) -> &[String];
}

pub fn filter_by_tag<'a, T: HasTags>(items: &'a [T], tag: Option<&str>) -> Vec<&'a T> {
    match tag {
        Some(t) => items
            .iter()
            .filter(|item| item.tags().contains(&t.to_string()))
            .collect(),
        None => items.iter().collect(),
    }
}
