[package]
name = "i-rs-fs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "File system operations CLI"
homepage = "https://github.com/i-rs/clis"

[dependencies]
clap.workspace = true
anyhow.workspace = true
