[package]
name = "i-rs-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Server management CLI"
homepage.workspace = true

[dependencies]
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
keyring.workspace = true
keyring-core.workspace = true
tabled.workspace = true
owo-colors.workspace = true
