use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // Locate workspace Cargo.toml (clis/Cargo.toml)
    let workspace_toml_path = Path::new(&manifest_dir)
        .join("../../Cargo.toml")
        .canonicalize()
        .expect("Failed to canonicalize workspace Cargo.toml path");
    let workspace_content = fs::read_to_string(&workspace_toml_path)
        .expect("Failed to read workspace Cargo.toml");
    let workspace_toml: toml::Value = toml::from_str(&workspace_content)
        .expect("Failed to parse workspace Cargo.toml");

    let members = workspace_toml["workspace"]["members"]
        .as_array()
        .expect("workspace.members should be an array");

    let workspace_root = workspace_toml_path.parent().unwrap();
    let mut tools = Vec::new();

    for member in members {
        let member_str = member.as_str().unwrap();

        // Only match crates/i-rs-{name} patterns (exclude core, api, and the meta crate itself)
        if let Some(name) = member_str.strip_prefix("crates/i-rs-") {
            if name == "core" || name == "api" || name.is_empty() {
                continue;
            }

            // Read the crate's Cargo.toml for description
            let crate_toml_path = workspace_root.join(member_str).join("Cargo.toml");
            let description = fs::read_to_string(&crate_toml_path)
                .ok()
                .and_then(|content| {
                    toml::from_str::<toml::Value>(&content).ok()
                })
                .and_then(|toml| {
                    toml.get("package")?
                        .get("description")?
                        .as_str()
                        .map(String::from)
                })
                .unwrap_or_default();

            tools.push((name.to_string(), description));
        }
    }

    // Sort by name for consistent ordering
    tools.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate Rust source
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("tools_gen.rs");

    let mut code = String::from(
        "// Auto-generated by build.rs — do not edit manually\n\
         pub fn generated_tools() -> &'static [(&'static str, &'static str)] {\n\
            &[\n",
    );
    for (name, desc) in &tools {
        // Escape double quotes in description
        let escaped_desc = desc.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("        (\"{name}\", \"{escaped_desc}\"),\n"));
    }
    code.push_str("    ]\n}\n");

    fs::write(&dest_path, code).expect("Failed to write tools_gen.rs");

    // Tell Cargo to rerun if workspace Cargo.toml or any crate's Cargo.toml changes
    println!("cargo:rerun-if-changed={}", workspace_toml_path.display());
    for member in members {
        let member_str = member.as_str().unwrap();
        if member_str.starts_with("crates/i-rs-") {
            let crate_toml = workspace_root.join(member_str).join("Cargo.toml");
            println!("cargo:rerun-if-changed={}", crate_toml.display());
        }
    }
}
