[package]
name = "i-rs-http"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "HTTP client CLI"

[dependencies]
clap.workspace = true
anyhow.workspace = true
reqwest.workspace = true
tokio.workspace = true
